volumes:
  data: {}
services:
  sqls:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - data:/var/opt/mssql
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=WmM4ng-ia
