@echo off
REM Edit as needed
SET WMUSF_SBX_MANUAL_TEMPLATE_ID=IP\1011\IS\DB_PPS_CDS_SqlServer02
SET WMUSF_SBX_MANUAL_FIXES_ZIP=K:\images\fixes\Platform\1011\Flavor02\2025-04-14\fixes.zip
SET WMUSF_SBX_MANUAL_INSTALL_HOME=x:\webMethods\IP_IS_PS2
SET WMUSF_SBX_MANUAL_INSTALLER_BIN=k:\installer.exe
SET WMUSF_SBX_MANUAL_PRODUCTS_ZIP=K:\images\products\Platform\1011\Flavor02\products.zip