@echo off

SET WMUSF_SBX_STARTUP_TEMPLATE=DBC\1011\full
SET WMUSF_SBX_STARTUP_INSTALL_DIR=%WMUSF_DBC_HOME%

SET WMUSF_SBX_STARTUP_INSTALLER_BINARY=
SET WMUSF_SBX_STARTUP_UM_BOOTSTRAP_BINARY=
SET WMUSF_SBX_STARTUP_PLATFORM_PRODUCTS_ZIP=
SET WMUSF_SBX_STARTUP_PLATFORM_FIXES_ZIP=

REM Optional, eventually set this to avoid user interaction
REM If not set, the sandbox will ask for user input

:: local test variables
:: SET WMUSF_SBX_WM_DOWNLOAD_USER=you@yourcompany.somedomain
:: SET WMUSF_SBX_WM_DOWNLOAD_PASS=yourpass

:: framework variables
::SET WMUSF_DOWNLOAD_USER=%WMUSF_SBX_WM_DOWNLOAD_USER%
::SET WMUSF_DOWNLOAD_PASSWORD=%WMUSF_SBX_WM_DOWNLOAD_PASS%
